apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestar-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: codestar-api

  template:
    metadata:
      labels:
        app: codestar-api

    spec:
      imagePullSecrets:
        - name: ghcr-registry-secret

      initContainers:
        - name: codestar-api-migrate
          image: ghcr.io/star-academy/summer1403-project-group02-backend:0.4.0
          imagePullPolicy: Always
          args: ["migrate"]
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: codestar-api-config
                  key: asp-environment

            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: codestar-api-secret
                  key: default-conn-str

          resources:
            limits:
              memory: "256Mi"
              cpu: "128m"

      containers:
        - name: codestar-api
          image: ghcr.io/star-academy/summer1403-project-group02-backend:0.4.0
          imagePullPolicy: Always
          args: ["run"]
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: codestar-api-config
                  key: asp-environment

            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: codestar-api-secret
                  key: default-conn-str

          resources:
            limits:
              memory: "256Mi"
              cpu: "128m"

          ports:
            - containerPort: 8080
