api:
  deployment:
    name: codestar-api
    replicaCount: 2
    image:
      name: ghcr.io/star-academy/summer1403-project-group02-backend
      pullPolicy: IfNotPresent
      tag: 0.4.0

  config:
    name: codestar-api-config
    asp_environment: Development

  service:
    name: codestar-api
    port: 80

  resources:
    limits:
      cpu: 256m
      memory: 256Mi
    requests:
      cpu: 128m
      memory: 128Mi

ingress:
  ingressClassName: nginx
  name: codestar-ingress
  rules:
    - host: codestar-g2.abriment.com
      path: /
      pathType: Prefix
      serviceName: codestar-api
      servicePort: 80
