apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
  labels:
    app: {{ .Values.frontend.deployment.name }}

spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.deployment.name }}

  replicas: {{ default 1 .Values.frontend.deployment.replicaCount }}

  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deployment.name }}

    spec:
      {{- if .Values.frontend.pullSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.frontend.pullSecret.name }}
      {{- end }}

      containers:
        - name: {{ .Values.frontend.deployment.name }}
          image: "{{ .Values.frontend.deployment.image.name }}:{{ .Values.frontend.deployment.image.tag }}"
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: {{ .Values.frontend.deployment.containerPort }}

          resources:
            {{- toYaml .Values.frontend.deployment.resources | nindent 12 }}

          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Values.frontend.config.name }}
            items:
              - key: nginx.conf
                path: nginx.conf