{{ $pullSecret := .Values.frontend.deployment.pullSecret }}
{{- if $pullSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pullSecret.name }}
data:
  .dockerconfigjson: {{ $pullSecret.data.dockerconfigjsonB64 }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
