apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    app: {{ .Values.frontend.service.name }}
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.deployment.containerPort }}

  selector:
    app: {{ .Values.frontend.deployment.name }}