{{ $app := .Values.frontend }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.service.name }}
  labels:
    app: {{ $app.service.name }}
spec:
  ports:
    - port: {{ $app.service.port }}
      targetPort: {{ $app.deployment.containerPort }}

  selector:
    app: {{ $app.deployment.name }}