{{ $pullSecret := .Values.api.deployment.pullSecret }}
{{- if $pullSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pullSecret.name }}
data:
  {{ $pullSecret.data | toYaml | nindent 2 }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
