{{ $secrets := .Values.api.secret }}
{{- if $secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secrets.name }}
type: Opaque
data:
  conn-str: {{ $secrets.data.conn_str | b64enc }}
{{ end }}
