apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  labels:
    app: {{ .Values.api.service.name }}

spec:
  selector:
    app: {{ .Values.api.deployment.name }}

  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.deployment.containerPort }}
