name: Validate k8s manifests
on:
  pull_request:
    paths:
      - "k8s/**"
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@latest

      - name: Validate Kubernetes manifests
        run: |
          kubeconform -strict -ignore-missing-schemas -summary k8s/