name: Build pr-conventional-commit

on:
    push:
        paths:
            - .github/actions/pr-conventional-commit/
            - .github/workflows/pr-conventional-commit-build.yaml

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm install --include=dev --prefix .github/actions/pr-conventional-commit/

            - name: Run build
              run: npm run --prefix .github/actions/pr-conventional-commit/ build

            - name: Commit changes
              uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
              with:
                  add: ".github/actions/pr-conventional-commit/dist"
                  message: "Build pr-conventional-commit"
